{==============================================================================
  Program:     dumpsql
  Purpose:     Prints the metadata SQL that a given provider version produces,
               as an isql script. Lets the queries be run against a real server
               without a GUI, which is how the Firebird 3 to 6 SQL is verified.
  Author:      Alexandros Ntermaris
  Created:     2026-08-20

  Usage:
    dumpsql [major] [minor] > queries.sql
    isql -user SYSDBA -password xxx -i queries.sql <database>

  The point is that the SQL comes from the real provider classes, not from a
  copy typed into a test script. A query that passes here is the query the
  program will actually send.
==============================================================================}
program dumpsql;

{$mode objfpc}{$H+}

uses
  SysUtils, ServerVersion, MetadataSqlProvider, MetadataSqlProviderFactory;

{------------------------------------------------------------------------------
  Emit
  ----------------------------------------------------------------------------
  Writes one labelled query to standard output as isql input.

  Parameters:
    ALabel - Name of the collection, echoed by the script so the output can be
             matched back to the query that produced it.
    ASql   - The query. An empty string means the feature does not exist on
             this version, which is reported rather than skipped silently.
------------------------------------------------------------------------------}
procedure Emit(const ALabel, ASql: string);
begin
  WriteLn;
  WriteLn('/* ==== ', ALabel, ' ==== */');
  if Trim(ASql) = '' then
  begin
    WriteLn('SELECT ''', ALabel, ': not available on this version'' AS SKIPPED',
      ' FROM RDB$DATABASE;');
    Exit;
  end;
  WriteLn('SELECT ''--- ', ALabel, ' ---'' AS SECTION FROM RDB$DATABASE;');
  WriteLn(ASql, ' ROWS 5;');
end;

var
  Version: TServerVersion;
  Provider: TMetadataSqlProvider;
  Major, Minor: Integer;
begin
  Major := StrToIntDef(ParamStr(1), 3);
  Minor := StrToIntDef(ParamStr(2), 0);

  Version := ParseEngineVersion(Format('%d.%d.0', [Major, Minor]), 13, 0);
  Provider := CreateMetadataSqlProvider(Version);
  try
    WriteLn('/* Metadata SQL for ', Version.DisplayText,
      ' - generated by dumpsql */');
    WriteLn('SET LIST ON;');
    WriteLn('SET ECHO OFF;');

    Emit('EngineVersion', Provider.EngineVersionSQL);
    Emit('DatabaseInfo', Provider.DatabaseInfoSQL);
    Emit('Schemas', Provider.SchemasSQL);
    Emit('Domains', Provider.DomainsSQL);
    Emit('Tables', Provider.TablesSQL);
    Emit('GlobalTemporaryTables', Provider.GlobalTemporaryTablesSQL);
    Emit('Views', Provider.ViewsSQL);
    Emit('Procedures', Provider.ProceduresSQL);
    Emit('Functions', Provider.FunctionsSQL);
    Emit('ExternalFunctions', Provider.ExternalFunctionsSQL);
    Emit('Packages', Provider.PackagesSQL);
    Emit('TriggersDML', Provider.TriggersSQL(tkDML));
    Emit('TriggersDatabase', Provider.TriggersSQL(tkDatabase));
    Emit('TriggersDDL', Provider.TriggersSQL(tkDDL));
    Emit('Generators', Provider.GeneratorsSQL);
    Emit('Exceptions', Provider.ExceptionsSQL);
    Emit('Indices', Provider.IndicesSQL);
    Emit('Roles', Provider.RolesSQL);
    Emit('Publications', Provider.PublicationsSQL);
    Emit('CharacterSets', Provider.CharacterSetsSQL);
    Emit('Collations', Provider.CollationsSQL);
    Emit('BlobFilters', Provider.BlobFiltersSQL);
    Emit('Users', Provider.UsersSQL);
    Emit('SystemTables', Provider.SystemTablesSQL);
    Emit('SystemDomains', Provider.SystemDomainsSQL);
    Emit('SystemIndices', Provider.SystemIndicesSQL);
  finally
    Provider.Free;
  end;
end.
